
import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Abdul Ahad
 */
public class Keyboard2 extends javax.swing.JFrame {

    private Robot robot;
    private boolean shiftSelected;
    private boolean ctrlSelected;
    private boolean altSelected;

    /**
     * Creates new form Keyboard2
     */
    public Keyboard2() {
        initComponents();
        try {
            robot = new Robot();
            boolean lockingKeyState = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
            if(lockingKeyState){
                setCapitalLetters();
                btncap.setSelected(true);
            }
        } catch (AWTException ex) {
            Logger.getLogger(Keyboard2.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
            System.exit(0);
        }
    }
   

    public void setCapitalLetters() {
        btna.setText("A");
        btnb.setText("B");
        btnc.setText("C");
        btnd.setText("D");
        btne.setText("E");
        btnf.setText("F");
        btng.setText("G");
        btnh.setText("H");
        btni.setText("I");
        btnj.setText("J");
        btnk.setText("K");
        btnl.setText("L");
        btnm.setText("M");
        btnn.setText("N");
        btno.setText("O");
        btnp.setText("P");
        btnq.setText("Q");
        btnr.setText("R");
        btns.setText("S");
        btnt.setText("T");
        btnu.setText("U");
        btnv.setText("V");
        btnw.setText("W");
        btnx.setText("X");
        btny.setText("Y");
        btnz.setText("Z");
        btn1.setText("1");
        btn2.setText("2");
        btn3.setText("3");
        btn4.setText("4");
        btn5.setText("5");
        btn6.setText("6");
        btn7.setText("7");
        btn8.setText("8");
        btn9.setText("9");
        btn0.setText("0");
    }

    public void setSimpleLetters() {

        btna.setText("a");
        btnb.setText("b");
        btnc.setText("c");
        btnd.setText("d");
        btne.setText("e");
        btnf.setText("f");
        btng.setText("g");
        btnh.setText("h");
        btni.setText("i");
        btnj.setText("j");
        btnk.setText("k");
        btnl.setText("l");
        btnm.setText("m");
        btnn.setText("n");
        btno.setText("o");
        btnp.setText("p");
        btnq.setText("q");
        btnr.setText("r");
        btns.setText("s");
        btnt.setText("t");
        btnu.setText("u");
        btnv.setText("v");
        btnw.setText("w");
        btnx.setText("x");
        btny.setText("y");
        btnz.setText("z");
        btn1.setText("1");
        btn2.setText("2");
        btn3.setText("3");
        btn4.setText("4");
        btn5.setText("5");
        btn6.setText("6");
        btn7.setText("7");
        btn8.setText("8");
        btn9.setText("9");
        btn0.setText("0");
    }
    private void actionKeyRelease(){
    if (shiftSelected){
        shiftSelected = false;
        robot.keyRelease(KeyEvent.VK_SHIFT);
        setSimpleLetters();
        btnshift.setSelected(false);
    }
    if (altSelected){
        altSelected = false;
        robot.keyRelease(KeyEvent.VK_ALT);      
        btnalt.setSelected(false);
    }
    if (ctrlSelected){
        ctrlSelected = false;
        robot.keyRelease(KeyEvent.VK_CONTROL);
        btnctrl.setSelected(false);
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btntab = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btna = new javax.swing.JButton();
        btns = new javax.swing.JButton();
        btnd = new javax.swing.JButton();
        btnf = new javax.swing.JButton();
        btng = new javax.swing.JButton();
        btnh = new javax.swing.JButton();
        btnj = new javax.swing.JButton();
        btnk = new javax.swing.JButton();
        btnl = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnq = new javax.swing.JButton();
        btnw = new javax.swing.JButton();
        btne = new javax.swing.JButton();
        btnr = new javax.swing.JButton();
        btnt = new javax.swing.JButton();
        btny = new javax.swing.JButton();
        btnu = new javax.swing.JButton();
        btni = new javax.swing.JButton();
        btno = new javax.swing.JButton();
        btnp = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btncap = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        btnz = new javax.swing.JButton();
        btnx = new javax.swing.JButton();
        btnc = new javax.swing.JButton();
        btnv = new javax.swing.JButton();
        btnb = new javax.swing.JButton();
        btnn = new javax.swing.JButton();
        btnm = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnshift = new javax.swing.JToggleButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnalt = new javax.swing.JToggleButton();
        btnctrl = new javax.swing.JToggleButton();
        btnspace = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        btnbspace = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setForeground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btn1.setBackground(new java.awt.Color(0, 255, 255));
        btn1.setForeground(new java.awt.Color(51, 51, 255));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1);

        btn2.setBackground(new java.awt.Color(0, 255, 255));
        btn2.setForeground(new java.awt.Color(51, 51, 255));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2);

        btn3.setBackground(new java.awt.Color(0, 255, 255));
        btn3.setForeground(new java.awt.Color(51, 51, 255));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3);

        btn4.setBackground(new java.awt.Color(0, 255, 255));
        btn4.setForeground(new java.awt.Color(51, 51, 255));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4);

        btn5.setBackground(new java.awt.Color(0, 255, 255));
        btn5.setForeground(new java.awt.Color(51, 51, 255));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5);

        btn6.setBackground(new java.awt.Color(0, 255, 255));
        btn6.setForeground(new java.awt.Color(51, 51, 255));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6);

        btn7.setBackground(new java.awt.Color(0, 255, 255));
        btn7.setForeground(new java.awt.Color(51, 51, 255));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7);

        btn8.setBackground(new java.awt.Color(0, 255, 255));
        btn8.setForeground(new java.awt.Color(51, 51, 255));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8);

        btn9.setBackground(new java.awt.Color(0, 255, 255));
        btn9.setForeground(new java.awt.Color(51, 51, 255));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9);

        btn0.setBackground(new java.awt.Color(0, 255, 255));
        btn0.setForeground(new java.awt.Color(51, 51, 255));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 750, 40));

        btntab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btntab.setForeground(new java.awt.Color(51, 51, 255));
        btntab.setText("tab");
        btntab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntabActionPerformed(evt);
            }
        });
        jPanel1.add(btntab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, 40));

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));
        jPanel4.setForeground(new java.awt.Color(51, 51, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btna.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btna.setForeground(new java.awt.Color(0, 51, 255));
        btna.setText("A");
        btna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaActionPerformed(evt);
            }
        });
        jPanel4.add(btna);

        btns.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btns.setForeground(new java.awt.Color(0, 51, 255));
        btns.setText("S");
        btns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsActionPerformed(evt);
            }
        });
        jPanel4.add(btns);

        btnd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnd.setForeground(new java.awt.Color(0, 51, 255));
        btnd.setText("D");
        btnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndActionPerformed(evt);
            }
        });
        jPanel4.add(btnd);

        btnf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnf.setForeground(new java.awt.Color(0, 51, 255));
        btnf.setText("F");
        btnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfActionPerformed(evt);
            }
        });
        jPanel4.add(btnf);

        btng.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btng.setForeground(new java.awt.Color(0, 51, 255));
        btng.setText("G");
        btng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngActionPerformed(evt);
            }
        });
        jPanel4.add(btng);

        btnh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnh.setForeground(new java.awt.Color(0, 51, 255));
        btnh.setText("H");
        btnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhActionPerformed(evt);
            }
        });
        jPanel4.add(btnh);

        btnj.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnj.setForeground(new java.awt.Color(0, 51, 255));
        btnj.setText("J");
        btnj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjActionPerformed(evt);
            }
        });
        jPanel4.add(btnj);

        btnk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnk.setForeground(new java.awt.Color(0, 51, 255));
        btnk.setText("K");
        btnk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkActionPerformed(evt);
            }
        });
        jPanel4.add(btnk);

        btnl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnl.setForeground(new java.awt.Color(0, 51, 255));
        btnl.setText("L");
        btnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlActionPerformed(evt);
            }
        });
        jPanel4.add(btnl);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 570, 40));

        jPanel5.setBackground(new java.awt.Color(0, 51, 255));
        jPanel5.setForeground(new java.awt.Color(51, 51, 255));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnq.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnq.setForeground(new java.awt.Color(0, 51, 255));
        btnq.setText("Q");
        btnq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqActionPerformed(evt);
            }
        });
        jPanel5.add(btnq);

        btnw.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnw.setForeground(new java.awt.Color(0, 51, 255));
        btnw.setText("W");
        btnw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwActionPerformed(evt);
            }
        });
        jPanel5.add(btnw);

        btne.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btne.setForeground(new java.awt.Color(0, 51, 255));
        btne.setText("E");
        btne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneActionPerformed(evt);
            }
        });
        jPanel5.add(btne);

        btnr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnr.setForeground(new java.awt.Color(0, 51, 255));
        btnr.setText("R");
        btnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrActionPerformed(evt);
            }
        });
        jPanel5.add(btnr);

        btnt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnt.setForeground(new java.awt.Color(0, 51, 255));
        btnt.setText("T");
        btnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntActionPerformed(evt);
            }
        });
        jPanel5.add(btnt);

        btny.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btny.setForeground(new java.awt.Color(0, 51, 255));
        btny.setText("Y");
        btny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyActionPerformed(evt);
            }
        });
        jPanel5.add(btny);

        btnu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnu.setForeground(new java.awt.Color(0, 51, 255));
        btnu.setText("U");
        btnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuActionPerformed(evt);
            }
        });
        jPanel5.add(btnu);

        btni.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btni.setForeground(new java.awt.Color(0, 51, 255));
        btni.setText("I");
        btni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniActionPerformed(evt);
            }
        });
        jPanel5.add(btni);

        btno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btno.setForeground(new java.awt.Color(0, 51, 255));
        btno.setText("O");
        btno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoActionPerformed(evt);
            }
        });
        jPanel5.add(btno);

        btnp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnp.setForeground(new java.awt.Color(0, 51, 255));
        btnp.setText("P");
        btnp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpActionPerformed(evt);
            }
        });
        jPanel5.add(btnp);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 620, 40));

        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 5, 0));
        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        btncap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncap.setForeground(new java.awt.Color(51, 51, 255));
        btncap.setText("caps lock");
        btncap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapActionPerformed(evt);
            }
        });
        jPanel1.add(btncap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 40));

        jPanel7.setBackground(new java.awt.Color(51, 51, 255));
        jPanel7.setForeground(new java.awt.Color(51, 51, 255));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnz.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnz.setForeground(new java.awt.Color(0, 51, 255));
        btnz.setText("Z");
        btnz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnzActionPerformed(evt);
            }
        });
        jPanel7.add(btnz);

        btnx.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnx.setForeground(new java.awt.Color(0, 51, 255));
        btnx.setText("X");
        btnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxActionPerformed(evt);
            }
        });
        jPanel7.add(btnx);

        btnc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnc.setForeground(new java.awt.Color(0, 51, 255));
        btnc.setText("C");
        btnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncActionPerformed(evt);
            }
        });
        jPanel7.add(btnc);

        btnv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnv.setForeground(new java.awt.Color(0, 51, 255));
        btnv.setText("V");
        btnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvActionPerformed(evt);
            }
        });
        jPanel7.add(btnv);

        btnb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnb.setForeground(new java.awt.Color(0, 51, 255));
        btnb.setText("B");
        btnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbActionPerformed(evt);
            }
        });
        jPanel7.add(btnb);

        btnn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnn.setForeground(new java.awt.Color(0, 51, 255));
        btnn.setText("N");
        btnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnActionPerformed(evt);
            }
        });
        jPanel7.add(btnn);

        btnm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnm.setForeground(new java.awt.Color(0, 51, 255));
        btnm.setText("M");
        btnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmActionPerformed(evt);
            }
        });
        jPanel7.add(btnm);

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 500, 40));

        jPanel8.setForeground(new java.awt.Color(51, 51, 255));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnshift.setBackground(new java.awt.Color(102, 102, 255));
        btnshift.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnshift.setForeground(new java.awt.Color(0, 51, 255));
        btnshift.setText("shift");
        btnshift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshiftActionPerformed(evt);
            }
        });
        jPanel8.add(btnshift);

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 40));

        jPanel10.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jPanel11.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        btnalt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnalt.setForeground(new java.awt.Color(51, 51, 255));
        btnalt.setText("alt");
        btnalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaltActionPerformed(evt);
            }
        });
        jPanel1.add(btnalt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 60, 40));

        btnctrl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnctrl.setForeground(new java.awt.Color(51, 51, 255));
        btnctrl.setText("ctrl");
        btnctrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnctrlActionPerformed(evt);
            }
        });
        jPanel1.add(btnctrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 40));

        btnspace.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnspace.setForeground(new java.awt.Color(51, 51, 255));
        btnspace.setText("SPACE");
        btnspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnspaceActionPerformed(evt);
            }
        });
        jPanel1.add(btnspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 600, 40));

        jPanel3.setForeground(new java.awt.Color(51, 51, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnbspace.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbspace.setForeground(new java.awt.Color(0, 51, 255));
        btnbspace.setText("backspace");
        btnbspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbspaceActionPerformed(evt);
            }
        });
        jPanel3.add(btnbspace);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_1);
        robot.keyRelease(KeyEvent.VK_1);

    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_2);
        robot.keyRelease(KeyEvent.VK_2);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_3);
        robot.keyRelease(KeyEvent.VK_3);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_4);
        robot.keyRelease(KeyEvent.VK_4);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_5);
        robot.keyRelease(KeyEvent.VK_5);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:\
        robot.keyPress(KeyEvent.VK_6);
        robot.keyRelease(KeyEvent.VK_6);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_7);
        robot.keyRelease(KeyEvent.VK_7);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_8);
        robot.keyRelease(KeyEvent.VK_8);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_9);
        robot.keyRelease(KeyEvent.VK_9);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_0);
        robot.keyRelease(KeyEvent.VK_0);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btntabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntabActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_TAB);
        robot.keyRelease(KeyEvent.VK_TAB);
    }//GEN-LAST:event_btntabActionPerformed

    private void btnqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_Q);
        robot.keyRelease(KeyEvent.VK_Q);
    }//GEN-LAST:event_btnqActionPerformed

    private void btnwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_W);
        robot.keyRelease(KeyEvent.VK_W);
    }//GEN-LAST:event_btnwActionPerformed

    private void btnaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaltActionPerformed
        // TODO add your handling code here:
        if (btnalt.isSelected()) {
            altSelected = true;
            robot.keyPress(KeyEvent.VK_ALT);
        } else {
            altSelected = false;
            robot.keyRelease(KeyEvent.VK_ALT);
        }
    }//GEN-LAST:event_btnaltActionPerformed

    private void btneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_E);
        robot.keyRelease(KeyEvent.VK_E);
    }//GEN-LAST:event_btneActionPerformed

    private void btnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_R);
        robot.keyRelease(KeyEvent.VK_R);
    }//GEN-LAST:event_btnrActionPerformed

    private void btntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_T);
        robot.keyRelease(KeyEvent.VK_T);
    }//GEN-LAST:event_btntActionPerformed

    private void btnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_Y);
        robot.keyRelease(KeyEvent.VK_Y);
    }//GEN-LAST:event_btnyActionPerformed

    private void btnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_U);
        robot.keyRelease(KeyEvent.VK_U);
    }//GEN-LAST:event_btnuActionPerformed

    private void btniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_I);
        robot.keyRelease(KeyEvent.VK_I);
    }//GEN-LAST:event_btniActionPerformed

    private void btnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_O);
        robot.keyRelease(KeyEvent.VK_O);
    }//GEN-LAST:event_btnoActionPerformed

    private void btnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_P);
        robot.keyRelease(KeyEvent.VK_P);
    }//GEN-LAST:event_btnpActionPerformed

    private void btnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_A);
        robot.keyRelease(KeyEvent.VK_A);
    }//GEN-LAST:event_btnaActionPerformed

    private void btnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_S);
        robot.keyRelease(KeyEvent.VK_S);
    }//GEN-LAST:event_btnsActionPerformed

    private void btndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_D);
        robot.keyRelease(KeyEvent.VK_D);
    }//GEN-LAST:event_btndActionPerformed

    private void btnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_F);
        robot.keyRelease(KeyEvent.VK_F);
    }//GEN-LAST:event_btnfActionPerformed

    private void btngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_G);
        robot.keyRelease(KeyEvent.VK_G);
    }//GEN-LAST:event_btngActionPerformed

    private void btnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_H);
        robot.keyRelease(KeyEvent.VK_H);
    }//GEN-LAST:event_btnhActionPerformed

    private void btnjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_J);
        robot.keyRelease(KeyEvent.VK_J);
    }//GEN-LAST:event_btnjActionPerformed

    private void btnkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_K);
        robot.keyRelease(KeyEvent.VK_K);
    }//GEN-LAST:event_btnkActionPerformed

    private void btnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_L);
        robot.keyRelease(KeyEvent.VK_L);
    }//GEN-LAST:event_btnlActionPerformed

    private void btnzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnzActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_Z);
        robot.keyRelease(KeyEvent.VK_Z);
    }//GEN-LAST:event_btnzActionPerformed

    private void btnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_X);
        robot.keyRelease(KeyEvent.VK_X);
    }//GEN-LAST:event_btnxActionPerformed

    private void btncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_C);
        robot.keyRelease(KeyEvent.VK_C);
    }//GEN-LAST:event_btncActionPerformed

    private void btnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_V);
        robot.keyRelease(KeyEvent.VK_V);
    }//GEN-LAST:event_btnvActionPerformed

    private void btnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_B);
        robot.keyRelease(KeyEvent.VK_B);
    }//GEN-LAST:event_btnbActionPerformed

    private void btnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_N);
        robot.keyRelease(KeyEvent.VK_N);
    }//GEN-LAST:event_btnnActionPerformed

    private void btnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_M);
        robot.keyRelease(KeyEvent.VK_M);
    }//GEN-LAST:event_btnmActionPerformed

    private void btnspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnspaceActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_SPACE);
        robot.keyRelease(KeyEvent.VK_SPACE);
    }//GEN-LAST:event_btnspaceActionPerformed

    private void btnshiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshiftActionPerformed
        // TODO add your handling code here:
        if (btnshift.isSelected()) {
            shiftSelected = true;
            robot.keyPress(KeyEvent.VK_SHIFT);
            setCapitalLetters();
        } else {
            shiftSelected = false;
            robot.keyRelease(KeyEvent.VK_SHIFT);
            setSimpleLetters();
        }
    }//GEN-LAST:event_btnshiftActionPerformed

    private void btnctrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnctrlActionPerformed
        // TODO add your handling code here:
        if (btnctrl.isSelected()) {
            ctrlSelected = true;
            robot.keyPress(KeyEvent.VK_CONTROL);
        } else {
            ctrlSelected = false;
            robot.keyRelease(KeyEvent.VK_CONTROL);
        }
    }//GEN-LAST:event_btnctrlActionPerformed

    private void btnbspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbspaceActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_BACK_SPACE);
        robot.keyRelease(KeyEvent.VK_BACK_SPACE);
    }//GEN-LAST:event_btnbspaceActionPerformed

    private void btncapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapActionPerformed
        // TODO add your handling code here:
         if (btncap.isSelected()) {
            robot.keyPress(KeyEvent.VK_CAPS_LOCK);
            robot.keyRelease(KeyEvent.VK_CAPS_LOCK);
            setCapitalLetters();
        } else {
            robot.keyPress(KeyEvent.VK_CAPS_LOCK);
            robot.keyRelease(KeyEvent.VK_CAPS_LOCK);
            setSimpleLetters();
        }
    }//GEN-LAST:event_btncapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Keyboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Keyboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Keyboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Keyboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Keyboard2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btna;
    private javax.swing.JToggleButton btnalt;
    private javax.swing.JButton btnb;
    private javax.swing.JButton btnbspace;
    private javax.swing.JButton btnc;
    private javax.swing.JToggleButton btncap;
    private javax.swing.JToggleButton btnctrl;
    private javax.swing.JButton btnd;
    private javax.swing.JButton btne;
    private javax.swing.JButton btnf;
    private javax.swing.JButton btng;
    private javax.swing.JButton btnh;
    private javax.swing.JButton btni;
    private javax.swing.JButton btnj;
    private javax.swing.JButton btnk;
    private javax.swing.JButton btnl;
    private javax.swing.JButton btnm;
    private javax.swing.JButton btnn;
    private javax.swing.JButton btno;
    private javax.swing.JButton btnp;
    private javax.swing.JButton btnq;
    private javax.swing.JButton btnr;
    private javax.swing.JButton btns;
    private javax.swing.JToggleButton btnshift;
    private javax.swing.JToggleButton btnspace;
    private javax.swing.JButton btnt;
    private javax.swing.JButton btntab;
    private javax.swing.JButton btnu;
    private javax.swing.JButton btnv;
    private javax.swing.JButton btnw;
    private javax.swing.JButton btnx;
    private javax.swing.JButton btny;
    private javax.swing.JButton btnz;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
